services:
  proxy:
    image: docker.io/haproxy:lts
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
      - ./certs:/usr/local/etc/haproxy/certs
    ports:
      - 443:443
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
  apache:
    image: docker.io/httpd:latest
  nginx:
    image: docker.io/nginx:latest
  client:
    image: ghcr.io/ppoi/devcontainer-images/base:latest
    user: vscode
    command: tail -f /dev/null
    cap_add:
      - NET_RAW
